FROM nginx
COPY html_test /usr/share/nginx/html
# This is from the example in the Docker Hub Nginx docs - was this supposed to be
# only PART of a Dockerfile, or is this the whole thing? Let's test it.